import types from '../types'

export const links = [
  types.links.SIGNUP,
  types.links.LOGIN,
  types.links.LOGOUT,
  types.links.PROFILE,
  types.links.HOME,
  types.links.MAP,
  types.links.SHOP,
  types.links.ACTIVATE,
  types.links.FORGOT_PASSWORD,
  types.links.RESET_PASSWORD,
  types.links.MANAGE_SHOPS,
  types.links.MANAGE_SITE,
  types.links.MY_SHOP,
  types.links.ORDERS
]

export const orderedLinks = {
  userManagement: [
    types.links.SIGNUP,
    types.links.LOGIN,
    types.links.PROFILE,
    types.links.LOGOUT
  ],
  navigation: [
    types.links.HOME,
    types.links.SHOP,
    types.links.MAP,
    types.links.ORDERS,
    types.links.MY_SHOP,
    types.links.MANAGE_SHOPS,
    types.links.MANAGE_SITE
  ]
}

export const accessRules = {
  [types.permissions.NOT_CONNECTED]: {
    [types.links.LOGIN]: true,
    [types.links.SIGNUP]: true,
    [types.links.LOGOUT]: false,
    [types.links.PROFILE]: false,
    [types.links.HOME]: true,
    [types.links.SHOP]: true,
    [types.links.CALENDAR]: true,
    [types.links.MAP]: true,
    [types.links.ACTIVATE]: true,
    [types.links.FORGOT_PASSWORD]: true,
    [types.links.RESET_PASSWORD]: true,
    [types.links.MANAGE_SHOPS]: false,
    [types.links.MANAGE_SITE]: false,
    [types.links.MY_SHOP]: false,
    [types.links.ORDERS]: false
  },
  [types.permissions.CONSUMER]: {
    [types.links.LOGIN]: false,
    [types.links.SIGNUP]: false,
    [types.links.LOGOUT]: true,
    [types.links.PROFILE]: true,
    [types.links.HOME]: true,
    [types.links.SHOP]: true,
    [types.links.CALENDAR]: true,
    [types.links.MAP]: true,
    [types.links.ACTIVATE]: false,
    [types.links.FORGOT_PASSWORD]: false,
    [types.links.RESET_PASSWORD]: false,
    [types.links.MANAGE_SHOPS]: false,
    [types.links.MANAGE_SITE]: false,
    [types.links.MY_SHOP]: false,
    [types.links.ORDERS]: false
  },
  [types.permissions.MANAGE_PRODUCTS]: {
    [types.links.LOGIN]: false,
    [types.links.SIGNUP]: false,
    [types.links.LOGOUT]: true,
    [types.links.PROFILE]: true,
    [types.links.HOME]: true,
    [types.links.SHOP]: true,
    [types.links.CALENDAR]: true,
    [types.links.MAP]: true,
    [types.links.ACTIVATE]: false,
    [types.links.FORGOT_PASSWORD]: false,
    [types.links.RESET_PASSWORD]: false,
    [types.links.MANAGE_SHOPS]: false,
    [types.links.MANAGE_SITE]: false,
    [types.links.MY_SHOP]: false,
    [types.links.ORDERS]: false
  },
  [types.permissions.MANAGE_PRODUCERS]: {
    [types.links.LOGIN]: false,
    [types.links.SIGNUP]: false,
    [types.links.LOGOUT]: true,
    [types.links.PROFILE]: true,
    [types.links.HOME]: true,
    [types.links.SHOP]: true,
    [types.links.CALENDAR]: true,
    [types.links.MAP]: true,
    [types.links.ACTIVATE]: false,
    [types.links.FORGOT_PASSWORD]: false,
    [types.links.RESET_PASSWORD]: false,
    [types.links.MANAGE_SHOPS]: false,
    [types.links.MANAGE_SITE]: false,
    [types.links.MY_SHOP]: true,
    [types.links.ORDERS]: false
  },
  [types.permissions.MANAGE_MANAGERS]: {
    [types.links.LOGIN]: false,
    [types.links.SIGNUP]: false,
    [types.links.LOGOUT]: true,
    [types.links.PROFILE]: true,
    [types.links.HOME]: true,
    [types.links.SHOP]: true,
    [types.links.CALENDAR]: true,
    [types.links.MAP]: true,
    [types.links.ACTIVATE]: false,
    [types.links.FORGOT_PASSWORD]: false,
    [types.links.RESET_PASSWORD]: false,
    [types.links.MANAGE_SHOPS]: true,
    [types.links.MANAGE_SITE]: false,
    [types.links.MY_SHOP]: false,
    [types.links.ORDERS]: false
  },
  [types.permissions.MANAGE_STAFF]: {
    [types.links.LOGIN]: false,
    [types.links.SIGNUP]: false,
    [types.links.LOGOUT]: true,
    [types.links.PROFILE]: true,
    [types.links.HOME]: true,
    [types.links.SHOP]: true,
    [types.links.CALENDAR]: true,
    [types.links.MAP]: true,
    [types.links.ACTIVATE]: false,
    [types.links.FORGOT_PASSWORD]: false,
    [types.links.RESET_PASSWORD]: false,
    [types.links.MANAGE_SHOPS]: true,
    [types.links.MANAGE_SITE]: false,
    [types.links.MY_SHOP]: false,
    [types.links.ORDERS]: false
  },
  [types.permissions.MANAGE_USERS]: {
    [types.links.LOGIN]: false,
    [types.links.SIGNUP]: false,
    [types.links.LOGOUT]: true,
    [types.links.PROFILE]: true,
    [types.links.HOME]: true,
    [types.links.SHOP]: true,
    [types.links.CALENDAR]: true,
    [types.links.MAP]: true,
    [types.links.ACTIVATE]: false,
    [types.links.FORGOT_PASSWORD]: false,
    [types.links.RESET_PASSWORD]: false,
    [types.links.MANAGE_SHOPS]: true,
    [types.links.MANAGE_SITE]: false,
    [types.links.MY_SHOP]: false,
    [types.links.ORDERS]: false
  },
  [types.permissions.MANAGE_REX]: {
    [types.links.LOGIN]: false,
    [types.links.SIGNUP]: false,
    [types.links.LOGOUT]: true,
    [types.links.PROFILE]: true,
    [types.links.HOME]: true,
    [types.links.SHOP]: true,
    [types.links.CALENDAR]: true,
    [types.links.MAP]: true,
    [types.links.ACTIVATE]: false,
    [types.links.FORGOT_PASSWORD]: false,
    [types.links.RESET_PASSWORD]: false,
    [types.links.MANAGE_SHOPS]: true,
    [types.links.MANAGE_SITE]: true,
    [types.links.MY_SHOP]: false,
    [types.links.ORDERS]: false
  }
}
