export const SEPARATOR = 'separator'

export const SIGNUP = 'signup'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const PROFILE = 'profile'

export const HOME = 'home'
export const SHOP = 'shop'
export const MAP = 'map'
export const CALENDAR = 'calendar'
export const ORDERS = 'orders'
export const PRODUCTS = 'products'
export const MY_SHOP = 'myShop'
export const MANAGE_SHOPS = 'manageShops'
export const MANAGE_SITE = 'manageSite'

export const CONFIRMATION_EMAIL_SENT = 'confirmationEmailSent'
export const ACTIVATE = 'activate'
export const FORGOT_PASSWORD = 'forgotPassword'
export const RESET_PASSWORD = 'resetPassword'
